{% set name = "snowflake-id" %}
{% set version = "1.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name.replace('-', '_') }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 4a4cd49508599aaa16488311f4b9121e9ac3bac57edff3e9f71b1d79086dbfe8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - pdm-backend
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}

test:
  imports:
    - snowflake
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/vd2org/snowflake
  summary: 'The Snowflake generator done right.'
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/vd2org/snowflake

extra:
  recipe-maintainers:
    - m-rossi
